fps: 60

mqtt:
  host: localhost
  port: 1883

  clientid: lightsd
  realm: lights

debug:
  enable: true
  port: 9000

pipelines:
  leds:
    count: 1200
    operations:
      - name: rainbow
        type: gradient
        config:
          gradient:
            - {c: "#ff0000", p: 0.000}
            - {c: "#d52a00", p: 0.066}
            - {c: "#ab5500", p: 0.132}
            - {c: "#ab7f00", p: 0.198}
            - {c: "#abab00", p: 0.264}
            - {c: "#56d500", p: 0.330}
            - {c: "#00ff00", p: 0.396}
            - {c: "#00d52a", p: 0.462}
            - {c: "#00AB55", p: 0.528}
            - {c: "#0056AA", p: 0.594}
            - {c: "#0000ff", p: 0.660}
            - {c: "#2a00d5", p: 0.726}
            - {c: "#5500ab", p: 0.792}
            - {c: "#7f0081", p: 0.858}
            - {c: "#ab0055", p: 0.924}
            - {c: "#ff0000", p: 1.000}
      - name: rotation
        type: rotation
        config:
          speed: 30.0
          source: rainbow
      - name: raindrops
        type: raindrops
        config:
          hue_min: 0.0
          hue_max: 360.0
          sat_min: 1.0
          sat_max: 1.0
          val_min: 1.0
          val_max: 1.0
          decay_min: 0.5
          decay_max: 2.0
          chance: 0.002
      - name: mixer
        type: mixer
        config:
          source1: rotation
          source2: raindrops
          mode: multiply
          speed: 0.5
      - name: adjustment
        type: adjustment
        config:
          source: mixer
          correction: '#FFB0F0' # Typical value for SMD5050 LEDs
          temperature: '#FFFFFB' # 5400 K
      - name: dimmer
        type: dimmer
        config:
          source: adjustment
          value: 1.0
      - name: blackout
        type: blackout
        config:
          source: dimmer
          from: 500
          to: 100
    output:
      type: shm
      source: blackout
      config:
        file: leds

  dots:
    count: 100
    operations:
      - name: raindrops
        type: raindrops
        config:
          hue_min: 0.0
          hue_max: 360.0
          sat_min: 1.0
          sat_max: 1.0
          val_min: 1.0
          val_max: 1.0
          decay_min: 0.5
          decay_max: 2.0
          chance: 0.002
    output:
      type: shm
      source: raindrops
      config:
        file: ledsx