language: go
go:
  - 1.7.x
  - master

addons:
  apt:
    packages:
      - libftdi-dev

install:
  - go get github.com/kovetskiy/manul
  - go get github.com/jteeuwen/go-bindata
  - manul -Q

script: go generate -x ./... & go build -x
